apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preprod

  # Secrets

  # Infrastructure

  # Services

# - ./ingress-api.yaml
# - ./cert-manager/clusterissuer-letsencrypt.yaml
# - ../../base/rabbitmq
# - ../../base/auth-api
# - ../../base/shop-api
# - ../../base/tyk
resources:
- ./secrets
- ../../base/ingresses
- ../../base/back-office
- ../../base/authentification-api



images:
- name: rg.fr-par.scw.cloud/registry-goodfood/authentification-api
  newName: rg.fr-par.scw.cloud/registry-goodfood/authentification-api
  newTag: sha-3bab2e5
- name: rg.fr-par.scw.cloud/registry-goodfood/back-office
  newName: rg.fr-par.scw.cloud/registry-goodfood/back-office
  newTag: sha-d1c96d3




patches:
- path: back-office/patch-deployment.yaml
  target:
    kind: Deployment
    name: back-office
- path: back-office/patch-ingress.yaml
  target:
    kind: Ingress
    name: back-office-ingress
- path: authentification-api/patch-deployment.yaml
  target:
    kind: Deployment
    name: authentification-api
