apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: preprod

  # Secrets

  # Infrastructure

  # Services

# - ./ingress-api.yaml
# - ./cert-manager/clusterissuer-letsencrypt.yaml
# - ../../base/auth-api
# - ../../base/shop-api
# - ../../base/tyk
resources:
- ./secrets
- ../../base/rabbitmq
- ../../base/ingresses
- ../../base/back-office
- ../../base/authentification-api
- ../../base/tyk
- ../../base/shop-api
- ../../base/order-api


images:
- name: rg.fr-par.scw.cloud/registry-goodfood/authentification-api
  newName: rg.fr-par.scw.cloud/registry-goodfood/authentification-api
  newTag: sha-eb7f02b
- name: rg.fr-par.scw.cloud/registry-goodfood/back-office
  newName: rg.fr-par.scw.cloud/registry-goodfood/back-office
  newTag: sha-f21525f
- name: rg.fr-par.scw.cloud/registry-goodfood/order-api
  newName: rg.fr-par.scw.cloud/registry-goodfood/order-api
  newTag: sha-62b3685
- name: rg.fr-par.scw.cloud/registry-goodfood/shop-api
  newName: rg.fr-par.scw.cloud/registry-goodfood/shop-api
  newTag: sha-5064619


patches:
- path: back-office/patch-deployment.yaml
  target:
    kind: Deployment
    name: back-office
- path: back-office/patch-ingress.yaml
  target:
    kind: Ingress
    name: back-office-ingress
- path: authentification-api/patch-deployment.yaml
  target:
    kind: Deployment
    name: authentification-api
- path: tyk/patch-ingress.yaml
  target:
    kind: Ingress
    name: tyk-ingress
- path: tyk/patch-configmap.yaml
  target:
    kind: ConfigMap
    name: tyk-gateway-config
- path: rabbitmq/patch-deployment.yaml
  target:
    kind: Deployment
    name: rabbitmq
- path: shop-api/patch-deployment.yaml
  target:
    kind: Deployment
    name: shop-api
- path: order-api/patch-deployment.yaml
  target:
    kind: Deployment
    name: order-api
