apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: back-office-ingress
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  rules:
    - host: dev.goodfood.test
      http:
        paths:
          - path: /bo
            pathType: Prefix
            backend:
              service:
                name: back-office
                port:
                  number: 80
