apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  selector:
    app: order-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: websocket
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP