apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ghcr-sealed-secret-prod.yaml
  - rabbitmq-sealed-secret.yaml
  - sealed-secret-db-prod.yaml
  - sealed-secret-jwt-prod.yaml
  - jwt-private-key-sealed.yaml
  - tyk-sealed-secret.yaml
  - items-db-sealed-secret.yaml
  - resend-sealed-secret.yaml
  - admin-email-sealed-secret.yaml
