# 05-tyk/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tyk-gateway
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tyk-gateway
  template:
    metadata:
      labels:
        app: tyk-gateway
    spec:
      containers:
      - name: tyk-gateway
        image: tykio/tyk-gateway:v5.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tyk-config
          mountPath: /opt/tyk-gateway/tyk.conf
          subPath: tyk.conf
        - name: tyk-apps
          mountPath: /opt/tyk-gateway/apps
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: tyk-config
        configMap:
          name: tyk-gateway-config
      - name: tyk-apps
        configMap:
          name: tyk-api-definition
