apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: shop-api
  template:
    metadata:
      labels:
        app: shop-api
    spec:
      containers:
        - name: shop-api
          image: rg.fr-par.scw.cloud/registry-goodfood/shop-api:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "1000m"
            limits:
              memory: "128Mi"
              cpu: "2000m"