---
monitoring_cluster:
  children:
    monitoring:
      hosts:
        192.168.1.158:

  vars:
    ansible_port: 22
    ansible_user: debian
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_k3s
    ansible_become: true
  
    api_endpoint: 192.168.1.158