all:
  vars:
    ansible_port: 22
    ansible_user: debian
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_k3s
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3

  children:

    minio_dev:
      hosts:
        192.168.1.157:

    minio_preprod:
      hosts:
        192.168.1.155:
