apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-office
spec:
  template:
    spec:
      containers:
      - name: back-office
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://preprod-api.goodfood.ovh"