apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-office
spec:
  template:
    spec:
      rules:
        - host: dev.goodfood.test
          http:
            paths:
              - path: /bo
                pathType: Prefix
                backend:
                  service:
                    name: back-office
                    port:
                      number: 80

        - host: preprod-admin.goodfood.ovh
          http:
            paths:
              - path: /bo
                pathType: Prefix
                backend:
                  service:
                    name: back-office
                    port:
                      number: 80
      containers:
      - name: back-office
        env:

        - name: NEXT_PUBLIC_AUTH_BASE_URL
          value: "http://localhost:3000/auth"

        - name: NEXT_PUBLIC_SHOP_BASE_URL
          value: "http://localhost:80"