$ANSIBLE_VAULT;1.1;AES256
35376238343464633834323432363364653863643838316635303734343931363666316335336236
6366613635653435376131353439656434643137383533610a616330346335653964386337343661
30636165356331313661663462363263333465626231303165323930383735336231353363633035
3938663861643266390a643362326362303439316366633831303137323131653065306165323434
39393935306666643861613135373538356534633539336662356239343338313532663239383762
61313362326330613765376461386661666538636130653839636630316130363665336664303039
36643739326434613565333835653735353166356464653063626163323334626664376238633261
39336430313963383735653165366436346338393066313138376132353234333262393436316631
35663936303332373230326265616630393865363239623336623333646431303862336430646638
63356537376336316436373364346266393062626434333034386362363766393661623165316563
30373339383730333063656264346165303532373536653463326339363230663532643064353839
34656536643364303637383761656435383965623233343065643332303735303965633965656436
64383666353939313263346464666339613137316139313230373831336532623362396664376135
31356138393764333264653432303532623733653136643634303534666533656233653538623033
61646661636261316539386462306531653631373062666266393530653035626566646131353762
37393330666535363135353834386634346361663130393431386133363137363335643563616366
61313631366134616238656662646339656366353464306535623332326666656666323237363661
64623137633963393634376139366133346266336431633365396434316263366436383033336265
31356665373266353933663637393837656462666161336332643665653137306636643162333037
66613665626330346531633137346563643465346261386663333337663231326133326163666666
64366137323635633134616263346437373133656262633165663036616434366561313931366231
64613565343036393836663534353735303663393663623032343931393265653833613635393936
38306464343862343638633066323830666533313963636234323065363838363064363333396332
38353962383737336533623839636433653465336361386563306437313263623462356139636461
61653264663933343664396430643539363237333334666639663334383437613330343562643237
31646436306134326562663530313632366435666637626665666534333934363665393633393936
37663636643137656366643832363334663331363033306531623035663332346439333038363266
66343839393430663333383461396333666261353931373161643161376133646537356134383732
64616166663333313830626234383037373634306238653030643733653739356361393735646236
34386336383232356636633938353066663863303333633566393630663665343265333766663530
64346364343131643737356637353964303637643036306431343933336166306432323262653131
37373538386639656638386262656431383666333161343636386231653264356431373431636335
33333938303730323961633036656230613434366534366165393062653334643137303036306165
36333764663237646531623735383864623739646365346339326338653533323839633539373765
61613962663766366530396365616637666335343730393838663833373131323066663965306538
64326466623465326533636134643430646362376137386630613136393863316661313738353633
66616137643730666164656238383665313461326666373235376462663534343061333239353032
36336633376339393431646161643763653230653939636637323336646564663834333630376637
38306131353535313130313263616535343136663464616431353132333432303935613737633565
39343938313336306233653630303966613437613964373035623537376638653065356262383165
37613132333332333935393735623962396236303235383365393465626130316434306236646565
63646363613161643634383863373332336634656337356465316130623264386236636233316161
35313939343462306433326135616134373561373833656234663566633762326238646238633264
64366566373262653862
